/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package functionnew;

/**
 *
 * @author wuj0394
 */
public class DerivativeAtPointGUI extends javax.swing.JFrame {

    /**
     * Creates new form DerivativeAtPointGUI
     */
    
    Function o;
    Derivative d;
    
    public DerivativeAtPointGUI(Function a) {
        o = a;
        d = new Derivative(o.input);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        OriginalF1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DerivativeF1 = new javax.swing.JLabel();
        derAPLabel = new javax.swing.JLabel();
        DerAP2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tanEq = new javax.swing.JLabel();
        Graph = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Original Function");

        OriginalF1.setText("jLabel3");

        jLabel4.setText("Derivative");

        DerivativeF1.setText("jLabel5");

        derAPLabel.setText("Derivative at point");

        DerAP2.setText("jLabel7");

        jLabel8.setText("Equation of tangent");

        tanEq.setText("jLabel9");

        Graph.setText("Graph");
        Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OriginalF1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addContainerGap(117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanEq)
                            .addComponent(derAPLabel)
                            .addComponent(jLabel8)
                            .addComponent(DerAP2)
                            .addComponent(DerivativeF1))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Graph)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OriginalF1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DerivativeF1)
                .addGap(18, 18, 18)
                .addComponent(derAPLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DerAP2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanEq)
                .addGap(18, 18, 18)
                .addComponent(Graph)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphActionPerformed
        // TODO add your handling code here:
        Graph G = new Graph(o,d);
        G.initializeWindow();
        
        
        
    }//GEN-LAST:event_GraphActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel DerAP2;
    public javax.swing.JLabel DerivativeF1;
    private javax.swing.JButton Graph;
    public javax.swing.JLabel OriginalF1;
    public javax.swing.JLabel derAPLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel tanEq;
    // End of variables declaration//GEN-END:variables
}
